AWSTemplateFormatVersion: 2010-09-09
Description:
  AWS Fargate cluster demo
Parameters:
  EcsClusterName:
    Type: String
    Default: flask-fargate-mlops-cluster

Resources:
  FargateDemoCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref EcsClusterName

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: flask-fargate-mlops-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: "arn:aws:iam::025066267638:role/ecs-task-role"
      TaskRoleArn: "arn:aws:iam::025066267638:role/ecs-task-role"
      ContainerDefinitions:
        - Name: "flask-fargate-mlops"
          Cpu: 256
          Memory: 512
          Image: "025066267638.dkr.ecr.us-east-1.amazonaws.com/mlops-assignment:latest"
          LinuxParameters:
            InitProcessEnabled: true
          PortMappings:
            - ContainerPort: 8000

  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: flask-fargate-mlops-service
      Cluster: !Ref EcsClusterName
      LaunchType: FARGATE
      PlatformVersion: LATEST
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: 1
      EnableExecuteCommand: true
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - "sg-05f4228a3bdc91223"
          Subnets:
            - "subnet-00a5fb15bab55d3e5"
            - "subnet-00c44ab9d1ad40aab"
      TaskDefinition: !Ref TaskDefinition


